name: akm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  extended_masked_text: ^2.3.1
  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.4
  intl: ^0.17.0
  modal_bottom_sheet: ^2.1.0
  file_picker: ^4.6.1
  flutter_form_builder: ^7.5.0
  form_builder_validators: ^8.3.0
  form_builder_phone_field: ^1.3.0
  form_builder_file_picker: ^2.3.0
  form_builder_extra_fields: ^8.3.0
  font_awesome_flutter: ^10.1.0
  day_night_switcher: ^0.2.0+1
  shared_preferences: ^2.0.15
  slide_digital_clock: ^1.0.2
  flutter_native_splash: ^2.2.6
  wave: ^0.2.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/search_section/
    - assets/images/add_debitur_section/
    - assets/images/splash_side/
    - assets/images/fixed_nonfixed/
    - assets/images/home/
    - assets/images/splash_screen/
    - assets/images/upload/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  background_image: assets/images/splash_screen/splash.png
