name: akm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  drawerbehavior: ^2.2.2
  extended_masked_text: ^2.3.1
  flutter:
    sdk: flutter
  get: 4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.4
  intl: ^0.17.0
  modal_bottom_sheet: ^2.1.0
  flutter_form_builder: ^7.5.0
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/search_section/
    - assets/images/add_debitur_section/
    - assets/images/splash_side/
    - assets/images/fixed_nonfixed/
    - assets/images/home/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
